version: '3.9'

services:
  web:
    image: nginx
    build: ./public/
    volumes: 
      - ./public:/usr/share/nginx/html
      - ./config:/etc/nginx/
      - ./Certificaten:/etc/nginx/ssl
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "443:443"
      - "8080:8080"

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    restart: always
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./config:/mosquitto/data
      - ./config:/mosquitto/log
    ports:
      - "1883:1883"
      - "1884:1884"
      - "9001:9001"

  mqtt_connect:
    build:
      context: .
      dockerfile: dockerfile
    command: python MQTTConnect.py
    volumes:
      - .:/app
    network_mode: "host"
    depends_on:
      - mosquitto