version: '3.9'

services:
  web:
    image: nginx
    build: ./public/
    volumes: 
      - ./public:/usr/share/nginx/html
      - ./config:/etc/nginx/
      - ./Certificaten:/etc/nginx/ssl
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "443:443"
      - "80:80"

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    restart: always
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./config:/mosquitto/data
      - ./config:/mosquitto/log
    ports:
      - "1883:1883"
      - "1884:1884"
      - "9001:9001"


 #--------------- gotta delete after v 
  mqtt_connect:
    build: .
    command: python MQTTConnect.py
    volumes:
      - .:/app
    network_mode: "host"  # Allow the container to use the host network
    depends_on:
      - mosquitto

  robot1:
    build: .
    command: python robot.py
    volumes:
      - .:/app
    network_mode: "host"  # Allow the container to use the host network
    depends_on:
      - mosquitto
      - mqtt_connect
  robot2:
    build: .
    command: python robot.py
    volumes:
      - .:/app
    network_mode: "host"  # Allow the container to use the host network
    depends_on:
      - mosquitto
      - mqtt_connect
  robot3:
    build: .
    command: python robot.py
    volumes:
      - .:/app
    network_mode: "host"  # Allow the container to use the host network
    depends_on:
      - mosquitto
      - mqtt_connect
  robot4:
    build: .
    command: python robot.py
    volumes:
      - .:/app
    network_mode: "host"  # Allow the container to use the host network
    depends_on:
      - mosquitto
      - mqtt_connect
  
